name: .NET

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.7.2'
    
    - name: Install .NET Framework Developer Pack
      run: |
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-4.7.2

    - name: Build
      run: dotnet build GoodBoy/GoodBoy.csproj
